export const GET_ORDERS_STARTED = "GET_ORDERS_STARTED";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";
export const UPDATE_ORDERS = "UPDATE_ORDERS";
export const DELETE_ORDERS = "DELETE_ORDERS";

