export const GET_MASTERS_STARTED = "GET_MASTERS_STARTED";
export const GET_MASTERS_SUCCESS = "GET_MASTERS_SUCCESS";
export const GET_MASTERS_FAILURE = "GET_MASTERS_FAILURE";
export const UPDATE_MASTERS = "UPDATE_MASTERS";
export const ADD_MASTER = "ADD_MASTER";
export const DELETE_MASTER = "DELETE_MASTER";

