export const CHECK_USER_TOKEN_STARTED = "CHECK_USER_TOKEN_STARTED";
export const CHECK_USER_TOKEN_SUCCESS = "CHECK_USER_TOKEN_SUCCESS";
export const CHECK_USER_TOKEN_FAILURE = "CHECK_USER_TOKEN_FAILURE";
export const LOG_IN_STARTED = "LOG_IN_STARTED";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";
export const LOG_OUT = "LOG_OUT";
export const UPDATE_USER_PARAMS = "UPDATE_USER_PARAMS";
