export const GET_PRICES_STARTED = "GET_PRICES_STARTED";
export const GET_PRICES_SUCCESS = "GET_PRICES_SUCCESS";
export const GET_PRICES_FAILURE = "GET_PRICES_FAILURE";
export const UPDATE_PRICES = "UPDATE_PRICES";
